### PR TITLE
x64

### PR DESCRIPTION
**Pull request by chcg**
- appveyor.yml config file for just npp build 
, see https://ci.appveyor.com/project/chcg/codealignment/build/13.1.7
, but this would overwrite your existing configuration done probably with appveyor webinterface

- adapted CodeAlignment.Npp and dependent projects to build for x64
- updated N++ plugin interface with data from https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/master/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure
- updated xunit to version="1.9.2"

### CODE REVIEW

**Review by CharlesElvira — APPROVED** [review]
I was able to compile code alignment x64.

**Comment by cpmcgrath** [comment]
Sorry about the delay looking at this. Planning to check it out today and hopefully do a release

**Comment by cpmcgrath** [comment]
Hmm, it seems pretty close but I'm getting the following exception. I think I just have to change ToInt32 to ToInt64

> `************** Exception Text **************
> System.OverflowException: Arithmetic operation resulted in an overflow.
>    at System.IntPtr.ToInt32()
>    at CMcG.CodeAlignment.FormKeyGrabber.WndProc(Message& m) in C:\Data\Projects\Extensions\codealignment\CodeAlignment.Common.WinForms\FormKeyGrabber.cs:line 68
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cpmcgrath** [comment]
Confirmed
`            && (m.LParam.ToInt64() == LEFT_CONTROL || m.LParam.ToInt64() == RIGHT_CONTROL))`
Fixes it (and still works in the 32 bit version). Can you update the Pull request and I'll merge it in.

**Comment by cpmcgrath** [comment]
Few more notes:
* Can you make the CodeAlignment.Npp x64 build use the "Any CPU" configurations of the Common Projects (Keeps the project configuration simple, and I like the idea of there only being a single CodeAlignment.Common.dll per version, while the current logic would have one that works with x64 & x86 and one that only works with x64)
* This is just me being pedantic, but this would be an ideal time to rename the CodeAlignment.Npp Any CPU configuration to x86. Just keeps the intent clear (even if it is still in the "Any CPU" Solution config)

* The appveyor config is fantastic - What I've always wanted! Although the Notepad++ x86 build is missing CodeAlignment.dll

**Comment by chcg** [comment]
@cpmcgrath 

- added the requested fix
- additionally updated nuget packages
- updated appveyor.yml to build with VS15 and VS17, unfortunately the build output isn't valid for N++,also my local build is ok.

Regarding AnyCPU:
- https://stackoverflow.com/questions/5229768/c-sharp-compiling-for-32-64-bit-or-for-any-cpu
- so just the "frontend" dll for N++ is x86 or x64 and the ones behind are AnyCPU, if I got it right.

**Review by cpmcgrath — COMMENTED** [review]
Reviewed changes, all looking good

**Comment by cpmcgrath** [comment]
Been playing around with appveyor configuration. I can't figure out why the result doesn't work for Notepad++. Still, it's great to be able to confirm the build works & have the tests run (Might give me the motivation to improve the test coverage!)

**Pull request merged**
